### ISSUE TITLE
imagekit-ckeditor5-plugin not installed

### ISSUE THREAD

**Issue by henkjelthoving** [imagekit-developer/ckeditor-plugin#2]
I am trying to run npm install --save-dev imagekit-ckeditor5-plugin in my folder but receive this errors:
"npm WARN [Source@1.0.0](mailto:Source@1.0.0) No description
npm WARN [Source@1.0.0](mailto:Source@1.0.0) No repository field."

and 
"fixed 0 of 3 vulnerabilities in 7 scanned packages
3 vulnerabilities required manual review and could not be updated"

I have created a custom build of ckeditor5 as described.

What am I doing wrong?

**Comment by cloudmeteor** [comment]
Hi, Please make sure that you are using nodejs version 12 and above.
